// Centralized property data used across the site
export interface Property {
  id: string;
  title: string;
  location: string;
  city: string;
  type: "plot" | "villa" | "apartment" | "commercial";
  status: "ongoing" | "completed" | "upcoming";
  price: string;
  priceValue: number; // for filtering
  area: string;
  areaValue: number; // in sq.ft for filtering
  bedrooms?: number;
  bathrooms?: number;
  description: string;
  shortDesc: string;
  image: string;
  images: string[];
  amenities: string[];
  floorPlanUrl?: string;
  brochureUrl?: string;
  videoUrl?: string;
  mapUrl?: string;
  highlights: string[];
}

export const properties: Property[] = [
  {
    id: "ak-chitra-vilasa-garden-city",
    title: "AK Chitra Vilasa Garden City",
    location: "Madhurawada",
    city: "Visakhapatnam",
    type: "plot",
    status: "ongoing",
    price: "₹25 Lakhs onwards",
    priceValue: 2500000,
    area: "150 - 300 sq.yds",
    areaValue: 1350,
    description: "Well planned and budget-friendly plot variations, giving investors the independent decision to select the ideal parcel for their dream home. Located in the rapidly developing Madhurawada area with excellent connectivity to IT hubs, schools, hospitals and the beach.",
    shortDesc: "Well planned, budget-friendly plots giving investors the freedom to choose.",
    image: "/AK.jpg",
    images: ["/AK.jpg"],
    amenities: ["Gated Community", "24/7 Security", "Children's Play Area", "Landscaped Gardens", "Wide Internal Roads", "Underground Drainage", "Overhead Water Tank", "Community Hall"],
    brochureUrl: "/AK Infra Big Brochure print file-1-1_compressed_compressed_11zon.pdf",
    highlights: ["VMRDA Approved Layout", "Clear Title & Documentation", "Close to IT Hub", "5 mins from NH-16", "Near International Schools", "Bank Loan Available"],
  },
  {
    id: "anand-vihar",
    title: "Anand Vihar",
    location: "Kommadi",
    city: "Visakhapatnam",
    type: "apartment",
    status: "ongoing",
    price: "₹18 Lakhs onwards",
    priceValue: 1800000,
    area: "2BHK & 3BHK",
    areaValue: 1080,
    bedrooms: 2,
    bathrooms: 2,
    description: "Anand Vihar is a premium apartment building with superior quality construction, a distinctive design and a spectacular location. These luxurious homes are conveniently located in Visakhapatnam near Gayatri College, Kommadi.",
    shortDesc: "Premium apartments with elegant lifestyle near Kommadi, Visakhapatnam.",
    image: "/images/projects/chitra-vilasa-1.jpg",
    images: ["/images/projects/chitra-vilasa-1.jpg"],
    amenities: ["Lift", "100% Vastu Compliant", "RCC Structure", "UPVC Windows", "Granite Kitchen", "Teak Wood Main Door", "Borewell Water Supply", "Modular Switches"],
    brochureUrl: "/Anand Vihar_1 (1).pdf",
    highlights: ["Near Gayatri College", "Kommadi Main Road", "Block A & Block B", "East/North/South Facing", "5 Passenger Lift", "Bank Loan Available"],
  },
  {
    id: "city-of-gold-by-iconica",
    title: "City of Gold by Iconica",
    location: "Kommadi",
    city: "Visakhapatnam",
    type: "plot",
    status: "ongoing",
    price: "₹30 Lakhs onwards",
    priceValue: 3000000,
    area: "167 - 333 sq.yds",
    areaValue: 1500,
    description: "Premium gated community plots by Iconica in Kommadi offering luxury living with world-class amenities and strategic location near IT corridor.",
    shortDesc: "Premium gated community plots with world-class amenities.",
    image: "/IMG_20260724_125441.jpg",
    images: ["/IMG_20260724_125441.jpg"],
    amenities: ["Gated Community", "Clubhouse", "Swimming Pool", "Gymnasium", "Children's Play Area", "Jogging Track", "24/7 Security", "Power Backup"],
    brochureUrl: "/Iconica City Of Gold_ Floor Plan Brochure_ 101124 (1).pdf",
    highlights: ["VMRDA Approved", "Near IT Corridor", "Premium Location", "High Appreciation", "All Amenities", "Bank Loan Available"],
  },
  {
    id: "cmr-karlan-grand",
    title: "CMR KARLAN GRAND",
    location: "Madhurawada",
    city: "Visakhapatnam",
    type: "apartment",
    status: "ongoing",
    price: "₹75 Lakhs onwards",
    priceValue: 7500000,
    area: "1450 - 2400 sq.ft",
    areaValue: 1450,
    bedrooms: 3,
    bathrooms: 2,
    description: "Premium apartments by CMR Group with grand living spaces, modern architecture and top-notch amenities in the heart of Madhurawada.",
    shortDesc: "Premium apartments with grand living spaces and modern architecture.",
    image: "/images/projects/chitra-vilasa-1.jpg",
    images: ["/images/projects/chitra-vilasa-1.jpg"],
    amenities: ["Swimming Pool", "Clubhouse", "Gymnasium", "Children's Play Area", "Power Backup", "24/7 Security", "Landscaped Gardens", "Indoor Games"],
    brochureUrl: "/CMR Karlan Grand - MVP, Rythu Bazar (1).pdf",
    highlights: ["RERA Registered", "Premium Location", "Vastu Compliant", "Home Loan Available", "Ready Infrastructure", "Reputed Builder"],
  },
  {
    id: "cmr-karlan-one",
    title: "CMR KARLAN One",
    location: "Madhurawada",
    city: "Visakhapatnam",
    type: "apartment",
    status: "ongoing",
    price: "₹65 Lakhs onwards",
    priceValue: 6500000,
    area: "1200 - 2000 sq.ft",
    areaValue: 1200,
    bedrooms: 2,
    bathrooms: 2,
    description: "Contemporary apartments designed for modern families with smart layouts and premium finishes in a prime Madhurawada location.",
    shortDesc: "Contemporary apartments with smart layouts for modern families.",
    image: "/images/projects/chitra-vilasa-1.jpg",
    images: ["/images/projects/chitra-vilasa-1.jpg"],
    amenities: ["Swimming Pool", "Gymnasium", "Clubhouse", "Jogging Track", "Children's Play Area", "24/7 Security", "Power Backup", "Rainwater Harvesting"],
    brochureUrl: "/CMR One By Karlan - Siripuram  (2).pdf",
    highlights: ["RERA Registered", "Smart Home Features", "Vastu Compliant", "Near IT Hub", "Home Loan Available", "Reputed Builder"],
  },
  {
    id: "cmr-karlan-residency",
    title: "CMR KARLAN RESIDENCY",
    location: "Madhurawada",
    city: "Visakhapatnam",
    type: "apartment",
    status: "completed",
    price: "₹55 Lakhs onwards",
    priceValue: 5500000,
    area: "1100 - 1800 sq.ft",
    areaValue: 1100,
    bedrooms: 2,
    bathrooms: 2,
    description: "Well-designed residential apartments offering comfortable living with excellent connectivity and modern amenities.",
    shortDesc: "Well-designed apartments with comfortable living and modern amenities.",
    image: "/images/projects/chitra-vilasa-1.jpg",
    images: ["/images/projects/chitra-vilasa-1.jpg"],
    amenities: ["Clubhouse", "Gymnasium", "Children's Play Area", "24/7 Security", "Power Backup", "Parking", "Landscaped Gardens", "Community Hall"],
    brochureUrl: "/CMR Karlan Residency - MVP, samatha (1).pdf",
    highlights: ["RERA Registered", "Ready to Move In", "Vastu Compliant", "Bank Loan Available", "Established Locality", "Reputed Builder"],
  },
  {
    id: "cmr-karlan-square",
    title: "CMR KARLAN SQUARE",
    location: "Kommadi",
    city: "Visakhapatnam",
    type: "commercial",
    status: "ongoing",
    price: "₹45 Lakhs onwards",
    priceValue: 4500000,
    area: "500 - 2000 sq.ft",
    areaValue: 500,
    description: "Premium commercial spaces ideal for offices, retail and business establishments in the growing Kommadi commercial hub.",
    shortDesc: "Premium commercial spaces for offices and retail in Kommadi.",
    image: "/images/projects/chitra-vilasa-1.jpg",
    images: ["/images/projects/chitra-vilasa-1.jpg"],
    amenities: ["Ample Parking", "Power Backup", "High-Speed Elevators", "24/7 Security", "Fire Safety", "Central AC", "Conference Rooms", "Food Court"],
    brochureUrl: "/CMR Karlan Square - Seethammadhara  (1).pdf",
    highlights: ["Prime Commercial Location", "High Footfall Area", "Near IT Corridor", "Bank Loan Available", "Flexible Layouts", "Reputed Builder"],
  },
  {
    id: "iconica-capitol-and-crown",
    title: "Iconica Capitol and Crown",
    location: "Kommadi",
    city: "Visakhapatnam",
    type: "villa",
    status: "ongoing",
    price: "₹1.5 Cr onwards",
    priceValue: 15000000,
    area: "2500 - 4000 sq.ft",
    areaValue: 2500,
    bedrooms: 4,
    bathrooms: 4,
    description: "Ultra-luxury villas by Iconica offering world-class living with premium finishes, private gardens and exclusive community amenities.",
    shortDesc: "Ultra-luxury villas with premium finishes and private gardens.",
    image: "/images/projects/chitra-vilasa-1.jpg",
    images: ["/images/projects/chitra-vilasa-1.jpg"],
    amenities: ["Private Garden", "Swimming Pool", "Clubhouse", "Gymnasium", "Tennis Court", "Concierge Service", "Smart Home", "EV Charging"],
    brochureUrl: "/Iconica Capitol - Brochure (1) (1).pdf",
    highlights: ["VMRDA Approved", "Ultra Luxury Segment", "Vastu Compliant", "Premium Gated Community", "Near IT Corridor", "Home Loan Available"],
  },
  {
    id: "integrals-sunrise-city",
    title: "Integral's Sunrise City",
    location: "Anandapuram",
    city: "Visakhapatnam",
    type: "villa",
    status: "ongoing",
    price: "₹85 Lakhs onwards",
    priceValue: 8500000,
    area: "1800 - 3200 sq.ft",
    areaValue: 1800,
    bedrooms: 3,
    bathrooms: 3,
    description: "Modern villas and premium residential plots with contemporary architecture, gated security and lush green landscaping. A perfect blend of luxury and nature.",
    shortDesc: "Modern villas with premium finishes designed for elevated living.",
    image: "/images/projects/sunrise-city.jpg",
    images: ["/images/projects/sunrise-city.jpg"],
    amenities: ["Swimming Pool", "Clubhouse", "Gymnasium", "Jogging Track", "Children's Play Area", "24/7 CCTV Surveillance", "Power Backup", "Rainwater Harvesting"],
    brochureUrl: "/Integral Broucher 28-Jan-2022 11-55-03-1 (1) (1).pdf",
    highlights: ["GVMC Approved", "Premium Gated Community", "Vastu Compliant", "East Facing Villas", "Surrounded by Greenery", "Home Loan from Top Banks"],
  },
  {
    id: "irise-prime",
    title: "Irise Prime",
    location: "Madhurawada",
    city: "Visakhapatnam",
    type: "apartment",
    status: "upcoming",
    price: "₹70 Lakhs onwards",
    priceValue: 7000000,
    area: "1300 - 2200 sq.ft",
    areaValue: 1300,
    bedrooms: 3,
    bathrooms: 2,
    description: "Upcoming premium apartment project offering contemporary design, spacious layouts and a prime location in Madhurawada.",
    shortDesc: "Contemporary premium apartments with spacious layouts.",
    image: "/images/projects/chitra-vilasa-1.jpg",
    images: ["/images/projects/chitra-vilasa-1.jpg"],
    amenities: ["Swimming Pool", "Gymnasium", "Clubhouse", "Rooftop Garden", "Children's Play Area", "24/7 Security", "Power Backup", "EV Charging"],
    highlights: ["Upcoming Project", "Prime Location", "Modern Design", "Pre-Launch Prices", "Reputed Builder", "Bank Loan Available"],
  },
  {
    id: "lorven-heights",
    title: "Lorven Heights",
    location: "Madhurawada",
    city: "Visakhapatnam",
    type: "apartment",
    status: "ongoing",
    price: "₹60 Lakhs onwards",
    priceValue: 6000000,
    area: "1200 - 1900 sq.ft",
    areaValue: 1200,
    bedrooms: 2,
    bathrooms: 2,
    description: "Elevated living with panoramic views, modern amenities and thoughtfully designed apartments in a growing residential zone.",
    shortDesc: "Elevated living with panoramic views and modern amenities.",
    image: "/Lorvens Heights Elevation.jpeg",
    images: ["/Lorvens Heights Elevation.jpeg"],
    amenities: ["Clubhouse", "Gymnasium", "Swimming Pool", "Children's Play Area", "Jogging Track", "24/7 Security", "Power Backup", "Landscaped Gardens"],
    brochureUrl: "/Floor Plan.jpeg",
    highlights: ["RERA Registered", "Panoramic Views", "Vastu Compliant", "Near Schools & Hospitals", "Home Loan Available", "Growing Locality"],
  },
  {
    id: "navayuga-plotting",
    title: "Navayuga Plotting",
    location: "Anandapuram",
    city: "Visakhapatnam",
    type: "plot",
    status: "ongoing",
    price: "₹15 Lakhs onwards",
    priceValue: 1500000,
    area: "100 - 250 sq.yds",
    areaValue: 900,
    description: "Affordable plotting project in Anandapuram with proper approvals and clear documentation. Ideal for first-time investors.",
    shortDesc: "Affordable plots with proper approvals for first-time investors.",
    image: "/images/projects/chitra-vilasa-1.jpg",
    images: ["/images/projects/chitra-vilasa-1.jpg"],
    amenities: ["Gated Community", "Wide Roads", "Street Lighting", "Underground Drainage", "24/7 Security", "Landscaped Entrance"],
    highlights: ["VMRDA Approved", "Budget Friendly", "Clear Title", "Developing Area", "High Appreciation", "Bank Loan Available"],
  },
  {
    id: "northstar-golden-valley",
    title: "NorthStar - Golden Valley",
    location: "Kommadi",
    city: "Visakhapatnam",
    type: "plot",
    status: "ongoing",
    price: "₹28 Lakhs onwards",
    priceValue: 2800000,
    area: "150 - 300 sq.yds",
    areaValue: 1350,
    description: "Premium gated community plots by NorthStar in the golden corridor of Kommadi with excellent investment potential.",
    shortDesc: "Premium gated plots in the golden corridor of Kommadi.",
    image: "/NORTH.jpg",
    images: ["/NORTH.jpg"],
    amenities: ["Gated Community", "Clubhouse", "Swimming Pool", "Jogging Track", "Children's Play Area", "24/7 Security", "Wide Roads", "Avenue Plantation"],
    brochureUrl: "/North Star Golden Valley (1).pdf",
    highlights: ["VMRDA Approved", "Near IT SEZ", "Premium Builder", "High ROI", "Gated & Secured", "Bank Loan Available"],
  },
  {
    id: "prasanthi-nilayam",
    title: "Prasanthi Nilayam",
    location: "Anandapuram",
    city: "Visakhapatnam",
    type: "plot",
    status: "completed",
    price: "₹12 Lakhs onwards",
    priceValue: 1200000,
    area: "100 - 200 sq.yds",
    areaValue: 900,
    description: "Peaceful residential plotting project offering tranquil living environment with essential infrastructure and clear documentation.",
    shortDesc: "Peaceful residential plots with tranquil living environment.",
    image: "/PRASANTI.jpg",
    images: ["/PRASANTI.jpg"],
    amenities: ["Gated Community", "Wide Roads", "Underground Drainage", "Street Lighting", "Parks", "24/7 Security"],
    highlights: ["Approved Layout", "Completed Project", "Clear Title", "Peaceful Location", "Affordable", "Ready for Construction"],
  },
  {
    id: "rudra-seniors",
    title: "Rudra Seniors",
    location: "Madhurawada",
    city: "Visakhapatnam",
    type: "apartment",
    status: "upcoming",
    price: "₹50 Lakhs onwards",
    priceValue: 5000000,
    area: "1000 - 1600 sq.ft",
    areaValue: 1000,
    bedrooms: 2,
    bathrooms: 2,
    description: "Specially designed senior living apartments with healthcare facilities, emergency services and community spaces for active retirement.",
    shortDesc: "Senior living apartments with healthcare and community spaces.",
    image: "/rudhra.jpg",
    images: ["/rudhra.jpg"],
    amenities: ["Healthcare Center", "Pharmacy", "Walking Paths", "Meditation Hall", "Library", "24/7 Emergency Service", "Community Kitchen", "Recreation Room"],
    brochureUrl: "/Rudra Senior Floor plans-1(1) (1).pdf",
    highlights: ["Senior-Friendly Design", "On-Site Healthcare", "Emergency Services", "Community Living", "Peaceful Environment", "Assisted Living Options"],
  },
  {
    id: "siri-nirman-blue-arena",
    title: "SIRI NIRMAN - Blue Arena",
    location: "Kommadi",
    city: "Visakhapatnam",
    type: "apartment",
    status: "ongoing",
    price: "₹68 Lakhs onwards",
    priceValue: 6800000,
    area: "1250 - 2100 sq.ft",
    areaValue: 1250,
    bedrooms: 3,
    bathrooms: 2,
    description: "Modern apartments by Siri Nirman with blue-themed architecture, premium interiors and resort-style amenities.",
    shortDesc: "Modern apartments with blue-themed architecture and resort-style amenities.",
    image: "/images/projects/chitra-vilasa-1.jpg",
    images: ["/images/projects/chitra-vilasa-1.jpg"],
    amenities: ["Swimming Pool", "Gymnasium", "Clubhouse", "Indoor Games", "Children's Play Area", "24/7 Security", "Power Backup", "Landscaped Gardens"],
    highlights: ["RERA Registered", "Unique Architecture", "Premium Interiors", "Near IT Corridor", "Home Loan Available", "Reputed Builder"],
    brochureUrl: "/Blue Arena (1) (1).pdf",
  },
  {
    id: "sss-dream-homes",
    title: "SSS Dream Homes",
    location: "Anandapuram",
    city: "Visakhapatnam",
    type: "villa",
    status: "ongoing",
    price: "₹72 Lakhs onwards",
    priceValue: 7200000,
    area: "1600 - 2800 sq.ft",
    areaValue: 1600,
    bedrooms: 3,
    bathrooms: 3,
    description: "Affordable luxury villas designed to fulfill your dream of owning a beautiful independent home with modern amenities.",
    shortDesc: "Affordable luxury villas for your dream independent home.",
    image: "/images/projects/chitra-vilasa-1.jpg",
    images: ["/images/projects/chitra-vilasa-1.jpg"],
    amenities: ["Gated Community", "Clubhouse", "Children's Play Area", "Jogging Track", "24/7 Security", "Power Backup", "Landscaped Gardens", "Community Hall"],
    highlights: ["VMRDA Approved", "Independent Villas", "Vastu Compliant", "Affordable Luxury", "Growing Location", "Home Loan Available"],
    brochureUrl: "/SSS HOMES (1).pdf",
  },
  {
    id: "sss-grand-homes",
    title: "SSS Grand Homes",
    location: "Anandapuram",
    city: "Visakhapatnam",
    type: "villa",
    status: "ongoing",
    price: "₹95 Lakhs onwards",
    priceValue: 9500000,
    area: "2000 - 3500 sq.ft",
    areaValue: 2000,
    bedrooms: 4,
    bathrooms: 3,
    description: "Grand independent villas with spacious layouts, premium finishes and expansive living areas for large families.",
    shortDesc: "Grand villas with spacious layouts and premium finishes.",
    image: "/images/projects/chitra-vilasa-1.jpg",
    images: ["/images/projects/chitra-vilasa-1.jpg"],
    amenities: ["Swimming Pool", "Clubhouse", "Gymnasium", "Tennis Court", "Children's Play Area", "24/7 Security", "Power Backup", "Landscaped Gardens"],
    highlights: ["VMRDA Approved", "Grand Living", "Premium Finishes", "Spacious Plots", "Home Loan Available", "Near Developing Hub"],
    brochureUrl: "/sss 2 (1).pdf",
  },
  {
    id: "sss-sunrise",
    title: "SSS Sunrise",
    location: "Anandapuram",
    city: "Visakhapatnam",
    type: "plot",
    status: "ongoing",
    price: "₹20 Lakhs onwards",
    priceValue: 2000000,
    area: "120 - 270 sq.yds",
    areaValue: 1080,
    description: "Sunrise-facing plots in a well-planned gated community offering excellent east-facing opportunities for home construction.",
    shortDesc: "Sunrise-facing plots in a well-planned gated community.",
    image: "/images/projects/chitra-vilasa-1.jpg",
    images: ["/images/projects/chitra-vilasa-1.jpg"],
    amenities: ["Gated Community", "Wide Roads", "Parks", "Street Lighting", "Underground Drainage", "24/7 Security"],
    highlights: ["East Facing Plots", "VMRDA Approved", "Well Planned Layout", "Affordable", "Growing Area", "Bank Loan Available"],
    brochureUrl: "/sss sun rise 2.pdf",
  },
  {
    id: "yaksha-abode",
    title: "Yaksha Abode",
    location: "Madhurawada",
    city: "Visakhapatnam",
    type: "apartment",
    status: "ongoing",
    price: "₹58 Lakhs onwards",
    priceValue: 5800000,
    area: "1150 - 1850 sq.ft",
    areaValue: 1150,
    bedrooms: 2,
    bathrooms: 2,
    description: "Thoughtfully designed apartments offering a perfect blend of comfort, convenience and connectivity in Madhurawada.",
    shortDesc: "Thoughtfully designed apartments blending comfort and convenience.",
    image: "/images/projects/chitra-vilasa-1.jpg",
    images: ["/images/projects/chitra-vilasa-1.jpg"],
    amenities: ["Clubhouse", "Gymnasium", "Children's Play Area", "24/7 Security", "Power Backup", "Landscaped Gardens", "Parking", "Rainwater Harvesting"],
    highlights: ["RERA Registered", "Prime Location", "Modern Design", "Vastu Compliant", "Home Loan Available", "Quality Construction"],
  },
  {
    id: "yaksha-pride",
    title: "Yaksha Pride",
    location: "Madhurawada",
    city: "Visakhapatnam",
    type: "apartment",
    status: "upcoming",
    price: "₹62 Lakhs onwards",
    priceValue: 6200000,
    area: "1200 - 2000 sq.ft",
    areaValue: 1200,
    bedrooms: 3,
    bathrooms: 2,
    description: "Upcoming premium apartment project with pride-worthy features, contemporary design and a landmark address in Madhurawada.",
    shortDesc: "Premium apartments with pride-worthy features and landmark address.",
    image: "/images/projects/chitra-vilasa-1.jpg",
    images: ["/images/projects/chitra-vilasa-1.jpg"],
    amenities: ["Swimming Pool", "Clubhouse", "Gymnasium", "Rooftop Garden", "Children's Play Area", "24/7 Security", "Power Backup", "Smart Home"],
    highlights: ["Upcoming Launch", "Pre-Launch Prices", "Premium Location", "Modern Architecture", "Bank Loan Available", "Reputed Builder"],
    brochureUrl: "/YAKSHA PRIDE BROCHURE WEB (1).pdf",
  },
];

export function getPropertyById(id: string): Property | undefined {
  return properties.find((p) => p.id === id);
}

export function filterProperties(filters: {
  type?: string;
  status?: string;
  minPrice?: number;
  maxPrice?: number;
  location?: string;
  search?: string;
}): Property[] {
  return properties.filter((p) => {
    if (filters.type && filters.type !== "all" && p.type !== filters.type) return false;
    if (filters.status && filters.status !== "all" && p.status !== filters.status) return false;
    if (filters.minPrice && p.priceValue < filters.minPrice) return false;
    if (filters.maxPrice && p.priceValue > filters.maxPrice) return false;
    if (filters.location && filters.location !== "all" && p.location !== filters.location) return false;
    if (filters.search) {
      const q = filters.search.toLowerCase();
      return (
        p.title.toLowerCase().includes(q) ||
        p.location.toLowerCase().includes(q) ||
        p.type.toLowerCase().includes(q)
      );
    }
    return true;
  });
}
