// Centralized property data used across the site
export interface Property {
  id: string;
  title: string;
  location: string;
  city: string;
  type: "plot" | "villa" | "apartment" | "commercial";
  status: "ongoing" | "completed" | "upcoming";
  price: string;
  priceValue: number; // for filtering
  area: string;
  areaValue: number; // in sq.ft for filtering
  bedrooms?: number;
  bathrooms?: number;
  description: string;
  shortDesc: string;
  image: string;
  images: string[];
  amenities: string[];
  floorPlanUrl?: string;
  brochureUrl?: string;
  videoUrl?: string;
  mapUrl?: string;
  highlights: string[];
}

export const properties: Property[] = [
  {
    id: "ak-chitra-vilasa-garden-city",
    title: "AK Chitra Vilasa Garden City",
    location: "Boyapalem",
    city: "Visakhapatnam",
    type: "apartment",
    status: "ongoing",
    price: "₹36 Lakhs onwards",
    priceValue: 3570000,
    area: "850 - 1350 sq.ft",
    areaValue: 850,
    bedrooms: 2,
    bathrooms: 2,
    description: "Chitra Vilasa Garden City by AK Constructions is a premium gated community spread across 1.3 acres in Boyapalem (opposite Narayana College). The G+5 structure has 136 apartments with 2 BHK (850-1100 sft) and 3 BHK (1185-1350 sft) options, East & West facing. Priced at just ₹4,200/sft with amenities charges of ₹3.5 Lakhs. GVMC approved with RERA applied, possession in 2026. Features 100% Vastu compliance, no common walls, wide corridors, cross ventilation, basement parking, and an exclusive 1729 sft clubhouse with gym, yoga room, function hall and indoor games.",
    shortDesc: "Affordable 136-apartment gated community at ₹4,200/sft opposite Narayana College.",
    image: "/AK.jpg",
    images: ["/AK.jpg"],
    amenities: ["Clubhouse (1729 sft)", "Gymnasium", "Yoga Room", "Function Hall", "Indoor Games", "Children's Play Area", "Parks & Open Spaces", "Basement Parking", "Power Backup", "24/7 Security", "Wide Corridors", "100% Cross Ventilation"],
    brochureUrl: "/AK Infra Big Brochure print file-1-1_compressed_compressed_11zon.pdf",
    highlights: ["GVMC Approved", "₹4,200/sft Only", "136 Flats, G+5 Floors", "2 & 3 BHK (850-1350 sft)", "100% Vastu Compliant", "No Common Walls", "Opposite Narayana College", "Possession 2026"],
  },
  {
    id: "anand-vihar",
    title: "Anand Vihar",
    location: "Kommadi",
    city: "Visakhapatnam",
    type: "apartment",
    status: "ongoing",
    price: "₹51 Lakhs onwards",
    priceValue: 5060000,
    area: "1100 - 1525 sq.ft",
    areaValue: 1100,
    bedrooms: 2,
    bathrooms: 2,
    description: "Anand Vihar is a premium residential project in Kommadi (near Gayatri Engineering College) with 2 blocks (A & B), 5 floors, and 3 flats per floor on a land extent of 1700 sq.yds. Offers 2 BHK (1100, 1125, 1135 sft) and 3 BHK (1475, 1525 sft) apartments with North, East & South facing options at ₹4,600/sft with amenities charges of ₹2 Lakhs. Features dedicated 70 sft car parking, 24/7 water supply, power backup, lift facility, CCTV surveillance, and security guard. Located in a rapidly developing locality with excellent connectivity to IT Hub and Madhurawada.",
    shortDesc: "2-block premium apartments at ₹4,600/sft near Gayatri College, Kommadi.",
    image: "/images/projects/chitra-vilasa-1.jpg",
    images: ["/images/projects/chitra-vilasa-1.jpg"],
    amenities: ["Dedicated Car Parking (70 sft)", "24/7 Water Supply", "Power Backup", "Lift Facility", "Spacious Staircase", "CCTV Surveillance", "Security Guard"],
    brochureUrl: "/Anand Vihar_1 (1).pdf",
    highlights: ["2 Blocks (A & B), 5 Floors", "2 & 3 BHK (1100-1525 sft)", "₹4,600/sft", "Amenities: ₹2 Lakhs", "N/E/S Facing Options", "Land: 1700 Sq.Yds", "Near Gayatri Engineering College", "UDS: 39-55 Sq.Yds"],
  },
  {
    id: "city-of-gold-by-iconica",
    title: "ICONICA – City of Gold",
    location: "Rushikonda",
    city: "Visakhapatnam",
    type: "villa",
    status: "ongoing",
    price: "₹2.5 Cr onwards",
    priceValue: 25000000,
    area: "300 - 1200 sq.yds",
    areaValue: 2700,
    bedrooms: 4,
    bathrooms: 4,
    description: "ICONICA – City of Gold is a prestigious 97-acre luxury villa community at Hill-3, Rushikonda featuring 205 exclusive Triplex Villas (G+2) with plot sizes ranging from 300 to 1200 sq.yds. The project boasts 70%+ open green spaces, a grand 50,000 sft clubhouse, and nature-centric amenities including Aroma Garden, Ethno Medicinal Garden, Lotus Pond, and Bird Bath Zones. Priced at ₹13,000/sft (negotiable) with East & West facing options. A signature project by Iconica Constructions offering ultra-luxury living where gold meets grandeur and nature meets luxury.",
    shortDesc: "97-acre luxury triplex villa community with 50,000 sft clubhouse at Rushikonda.",
    image: "/IMG_20260724_125441.jpg",
    images: ["/IMG_20260724_125441.jpg"],
    amenities: ["Grand Clubhouse (50,000 sft)", "Swimming Pool", "Aroma Garden", "Ethno Medicinal Garden", "Lotus Pond", "Bird Bath Zones", "Palm Court", "Jogging Track", "Outdoor Gym", "Reflexology Path", "Yoga Pavilion", "Children's Play Area", "Pet Park", "Skating Rink", "Senior Citizens Park", "Barbeque Pavilion", "Sculpture Court", "Gazebo", "Chess & Hopscotch Courts", "24/7 Security", "CCTV Surveillance"],
    brochureUrl: "/Iconica City Of Gold_ Floor Plan Brochure_ 101124 (1).pdf",
    highlights: ["97 Acres Township", "205 Exclusive Triplex Villas", "₹13,000/sft (Negotiable)", "300-1200 Sq.Yds Plots", "50,000 sft Clubhouse", "70%+ Open Green Spaces", "East & West Facing", "Near IT SEZ & City Center"],
  },
  {
    id: "cmr-karlan-grand",
    title: "CMR KARLAN GRAND",
    location: "MVP Colony",
    city: "Visakhapatnam",
    type: "apartment",
    status: "ongoing",
    price: "₹1.55 Cr onwards",
    priceValue: 15480000,
    area: "1720 - 2680 sq.ft",
    areaValue: 1720,
    bedrooms: 3,
    bathrooms: 2,
    description: "Karlan Grand is a premium 15-floor residential project in MVP Colony (near Rythu Bazar) with 163 spacious 3 BHK apartments ranging from 1720 to 2680 sft. Priced at ₹9,000–₹10,000/sft (price increases from lower to higher floors). Below 2000 sft: ₹7 Lakhs (1 car parking + amenities); above 2000 sft: ₹8 Lakhs (2 car parking + amenities). Features swimming pool, gym, multipurpose hall, landscaped gardens, and modern elevation with premium finish. Located in the well-developed MVP Colony close to beachside area with excellent connectivity.",
    shortDesc: "Premium 15-floor, 163-apartment project near Rythu Bazar, MVP Colony.",
    image: "/CMR.jpg",
    images: ["/CMR.jpg"],
    amenities: ["Swimming Pool", "Gymnasium", "Children's Play Area", "Walking & Jogging Tracks", "Landscaped Gardens", "Multipurpose Hall", "Grand Entrance Lobby", "Seating & Leisure Areas", "Lift Facility", "Power Backup", "CCTV Surveillance", "24/7 Security"],
    brochureUrl: "/CMR Karlan Grand - MVP, Rythu Bazar (1).pdf",
    highlights: ["15 Floors, 163 Flats", "3 BHK: 1720-2680 sft", "₹9,000-₹10,000/sft", "Near Rythu Bazar, MVP Colony", "Close to Beachside", "1-2 Car Parking Included", "Family-Friendly Environment", "Premium Modern Elevation"],
  },
  {
    id: "cmr-karlan-one",
    title: "CMR ONE BY KARLAN",
    location: "Siripuram",
    city: "Visakhapatnam",
    type: "apartment",
    status: "ongoing",
    price: "₹2.06 Cr onwards",
    priceValue: 20608000,
    area: "1840 - 4595 sq.ft",
    areaValue: 1840,
    bedrooms: 3,
    bathrooms: 3,
    description: "CMR One by Karlan is an iconic 28-floor ultra-luxury high-rise in Siripuram — Vizag's first staggered high-rise and a premium landmark. With 143 spacious apartments from 1840 to 4595 sft, priced at ₹11,200–₹13,200/sft (increases with floor level). Features a grand ~30,000 sft clubhouse, premium commercial spaces on lower floors, high-end reception lounge, terrace gardens, and co-working spaces. Below 4000 sft: ₹8 Lakhs (2 car parking + amenities); above 4000 sft: ₹10 Lakhs (3 car parking + amenities). Close to beach with coastal views in the heart of the city.",
    shortDesc: "Vizag's first 28-floor staggered high-rise with 30,000 sft clubhouse in Siripuram.",
    image: "/images/projects/chitra-vilasa-1.jpg",
    images: ["/images/projects/chitra-vilasa-1.jpg"],
    amenities: ["Grand Clubhouse (~30,000 sft)", "Swimming Pool", "Gymnasium", "Indoor Games & Recreation", "Walking Tracks", "Terrace Gardens & Leisure Decks", "Multipurpose Hall", "Co-working Spaces", "Premium Commercial Spaces", "High-Speed Lifts", "Power Backup", "CCTV Surveillance", "24/7 Security", "Grand Reception Lounge"],
    brochureUrl: "/CMR One By Karlan - Siripuram  (2).pdf",
    highlights: ["28 Floors, 143 Flats", "Vizag's First Staggered High-Rise", "1840-4595 sft Apartments", "₹11,200-₹13,200/sft", "~30,000 sft Clubhouse", "Near Beach & Coastal Views", "Premium Siripuram Location", "2-3 Car Parking Included"],
  },
  {
    id: "cmr-karlan-residency",
    title: "CMR KARLAN RESIDENCY",
    location: "MVP Colony",
    city: "Visakhapatnam",
    type: "apartment",
    status: "ongoing",
    price: "₹1.27 Cr onwards",
    priceValue: 12745500,
    area: "1465 - 2045 sq.ft",
    areaValue: 1465,
    bedrooms: 3,
    bathrooms: 2,
    description: "Karlan Residency is a premium 16-floor high-rise in MVP Colony with 125 spacious 3 BHK apartments ranging from 1465 to 2045 sft. Priced at ₹8,700–₹9,700/sft (price increases with floor level). Features a grand ~10,000 sft clubhouse with swimming pool, gym, indoor games, and walking tracks. Parking includes 2 stilt floors + 3 basement levels. Below 2000 sft flats: ₹7 Lakhs (1 car parking + amenities); above 2000 sft: ₹8 Lakhs (2 car parking + amenities). Located near the beachside zone in a peaceful premium residential environment with modern architecture.",
    shortDesc: "Premium 16-floor, 125-apartment high-rise with 10,000 sft clubhouse in MVP Colony.",
    image: "/Reidency.jpg",
    images: ["/Reidency.jpg"],
    amenities: ["Grand Clubhouse (~10,000 sft)", "Swimming Pool", "Gymnasium", "Indoor Games", "Walking Tracks", "Landscaped Gardens", "Children's Play Area", "Terrace Seating & Leisure", "High-Speed Lifts", "Power Backup", "CCTV Surveillance", "24/7 Security", "2 Stilt + 3 Basement Parking"],
    brochureUrl: "/CMR Karlan Residency - MVP, samatha (1).pdf",
    highlights: ["16 Floors, 125 Flats", "3 BHK: 1465-2045 sft", "₹8,700-₹9,700/sft", "~10,000 sft Clubhouse", "Near Beachside Zone", "2 Stilt + 3 Basement Parking", "Prime MVP Colony Location", "Modern Architecture"],
  },
  {
    id: "cmr-karlan-square",
    title: "CMR KARLAN SQUARE",
    location: "Seethammadhara",
    city: "Visakhapatnam",
    type: "apartment",
    status: "ongoing",
    price: "₹1.58 Cr onwards",
    priceValue: 15840000,
    area: "1440 - 1765 sq.ft",
    areaValue: 1440,
    bedrooms: 3,
    bathrooms: 2,
    description: "Karlan Square is a premium 16-floor high-rise residential project in Seethammadhara with 80 luxury 3 BHK apartments ranging from 1440 to 1765 sft. Priced at ₹11,000–₹12,000/sft (negotiable) with East, West & North facing options. Features a 7,500 sft premium clubhouse with gym, landscaped gardens, children's play area, and walking tracks. 1440 sft flats include 1 car parking + amenities at ₹6 Lakhs; remaining flats include 2 car parking + amenities at ₹7 Lakhs. Located in the prime area of Seethammadhara with excellent connectivity to schools, hospitals, and shopping centers.",
    shortDesc: "Premium 16-floor, 80-apartment high-rise with 7,500 sft clubhouse in Seethammadhara.",
    image: "/Square.jpg",
    images: ["/Square.jpg"],
    amenities: ["Clubhouse (7,500 sft)", "Gymnasium", "Landscaped Gardens", "Walking Tracks", "Children's Play Area", "Seating & Leisure Spaces", "Lift Facility", "Power Backup", "CCTV Surveillance", "24/7 Security"],
    brochureUrl: "/CMR Karlan Square - Seethammadhara  (1).pdf",
    highlights: ["16 Floors, 80 Flats", "3 BHK: 1440-1765 sft", "₹11,000-₹12,000/sft", "7,500 sft Clubhouse", "East, West & North Facing", "Prime Seethammadhara Location", "1-2 Car Parking Included", "High Investment Returns"],
  },
  {
    id: "iconica-capitol-and-crown",
    title: "ICONICA – Capitol & The Crown",
    location: "Madhurawada",
    city: "Visakhapatnam",
    type: "apartment",
    status: "ongoing",
    price: "₹1.3 Cr onwards",
    priceValue: 12760000,
    area: "1595 - 5285 sq.ft",
    areaValue: 1595,
    bedrooms: 3,
    bathrooms: 3,
    description: "ICONICA – Capitol & The Crown is a mega luxury gated community by Iconica Constructions located at IT SEZ, Law College Road near Panorama Hills. Spread across 7.1 acres with 10 luxury towers, the project offers 100% East-facing homes ranging from 2 BHK (1595 sft) to 5 BHK Duplex (5285 sft). Features a grand 33,000 sft clubhouse with fitness, wellness, recreation and community spaces. Two luxury segments — Capitol at ₹8,000/sft and Crown at ₹10,000/sft (negotiable) with ₹12 Lakhs amenity charges. Resort-style landscaping with reflexology path, pet park, skating rink, barbeque pavilion, and more.",
    shortDesc: "Mega luxury 10-tower gated community with 33,000 sft clubhouse near IT SEZ.",
    image: "/iconic.jpg",
    images: ["/iconic.jpg"],
    amenities: ["Grand Clubhouse (33,000 sft)", "Swimming Pool", "Gymnasium", "Yoga & Meditation Pavilion", "Indoor Games", "Reflexology Path with Skating", "Palm Court", "Children's Play Area", "Pet Park", "Skating Rink", "Floral Garden", "Senior Citizens Park", "Barbeque Pavilion", "Sculpture Court", "Swing Park", "Gazebo", "Chess & Hopscotch Courts", "24/7 Security", "CCTV Surveillance"],
    brochureUrl: "/Iconica Capitol - Brochure (1) (1).pdf",
    highlights: ["7.1 Acres, 10 Towers", "2/3/4/5 BHK (1595-5285 sft)", "Capitol: ₹8,000/sft", "Crown: ₹10,000/sft", "33,000 sft Clubhouse", "100% East Facing", "Near IT SEZ & Panorama Hills", "Simplex & Duplex Options"],
  },
  {
    id: "integrals-sunrise-city",
    title: "Integral's Sunrise City",
    location: "Anandapuram",
    city: "Visakhapatnam",
    type: "apartment",
    status: "ongoing",
    price: "₹60 Lakhs onwards",
    priceValue: 5980000,
    area: "1150 - 3320 sq.ft",
    areaValue: 1150,
    bedrooms: 2,
    bathrooms: 2,
    description: "Integral Sunrise City is a premium RERA-approved gated community spread across 4.1 acres with G+5 structure and basement parking. The project has 4 blocks (A, B, C & D) with 336 total apartments offering 2 BHK (1150 sft), 3 BHK (1430 & 1500 sft), and 4 BHK (3320 sft) options. Priced at ₹5,200/sft (negotiable) with amenities charges of ₹5 Lakhs. Features a grand 17,000 sft G+2 clubhouse with swimming pool, gym, spa, conference hall, function hall, library, and indoor games. 100% Vastu compliant with cross ventilation, wide corridors, and large open spaces. Just 5 minutes from schools, hospitals, and near Gayatri Medical College.",
    shortDesc: "RERA-approved 336 apartments across 4.1 acres with 17,000 sft clubhouse.",
    image: "/integral-project.jpg",
    images: ["/integral-project.jpg"],
    amenities: ["Clubhouse (17,000 sft, G+2)", "Swimming Pool", "Gymnasium", "Spa", "Beauty Parlour & Salon", "Conference Hall", "Function Hall", "Library", "Yoga Room", "Kids Play Area", "Departmental Store", "Clinic & Medical Store", "Table Tennis", "Snooker", "Chess & Carrom", "Indoor Games", "Basement Car Parking", "24/7 Security", "Power Backup", "Landscaped Parks"],
    brochureUrl: "/integral.pdf",
    highlights: ["RERA Approved", "4.1 Acres, 336 Apartments", "₹5,200/sft (Negotiable)", "2/3/4 BHK (1150-3320 sft)", "17,000 sft Clubhouse", "100% Vastu Compliant", "Near Gayatri Medical College", "Home Loan Available"],
  },
  {
    id: "irise-prime",
    title: "Irise Prime",
    location: "Madhurawada",
    city: "Visakhapatnam",
    type: "apartment",
    status: "upcoming",
    price: "₹70 Lakhs onwards",
    priceValue: 7000000,
    area: "1300 - 2200 sq.ft",
    areaValue: 1300,
    bedrooms: 3,
    bathrooms: 2,
    description: "Upcoming premium apartment project offering contemporary design, spacious layouts and a prime location in Madhurawada.",
    shortDesc: "Contemporary premium apartments with spacious layouts.",
    image: "/images/projects/chitra-vilasa-1.jpg",
    images: ["/images/projects/chitra-vilasa-1.jpg"],
    amenities: ["Swimming Pool", "Gymnasium", "Clubhouse", "Rooftop Garden", "Children's Play Area", "24/7 Security", "Power Backup", "EV Charging"],
    highlights: ["Upcoming Project", "Prime Location", "Modern Design", "Pre-Launch Prices", "Reputed Builder", "Bank Loan Available"],
  },
  {
    id: "lorven-heights",
    title: "Lorven Heights",
    location: "Madhurawada",
    city: "Visakhapatnam",
    type: "commercial",
    status: "ongoing",
    price: "₹1.64 Cr onwards",
    priceValue: 16445000,
    area: "1265 sq.ft",
    areaValue: 1265,
    description: "Lorven Heights is a premium fully commercial building with 5 floors and 20 commercial units (4 per floor), each 1265 sft. Priced at ₹13,000/sft (negotiable) with basement car parking (80 sft per unit). Total land extent of 893 sq.yds with UDS of 44.65 sq.yds. Available units: 403 & 404 (South Facing). Ideal for offices, clinics, showrooms and corporate businesses with excellent investment potential and high rental demand.",
    shortDesc: "Premium 5-floor commercial building with 1265 sft units at ₹13,000/sft.",
    image: "/Lorvens Heights Elevation.jpeg",
    images: ["/Lorvens Heights Elevation.jpeg"],
    amenities: ["Basement Car Parking", "Modern Construction", "Quality Finishes", "Lift Facility", "Power Backup", "24/7 Security"],
    brochureUrl: "/Floor Plan.jpeg",
    highlights: ["Fully Commercial Building", "5 Floors, 20 Units", "1265 sft per Unit", "₹13,000/sft (Negotiable)", "Land: 893 Sq.Yds", "UDS: 44.65 Sq.Yds", "Available: 403 & 404 (South)", "High Rental Demand"],
  },
  {
    id: "navayuga-plotting",
    title: "Navayuga Plotting",
    location: "Anandapuram",
    city: "Visakhapatnam",
    type: "plot",
    status: "ongoing",
    price: "₹15 Lakhs onwards",
    priceValue: 1500000,
    area: "100 - 250 sq.yds",
    areaValue: 900,
    description: "Affordable plotting project in Anandapuram with proper approvals and clear documentation. Ideal for first-time investors.",
    shortDesc: "Affordable plots with proper approvals for first-time investors.",
    image: "/plotting.jpg",
    images: ["/plotting.jpg"],
    amenities: ["Gated Community", "Wide Roads", "Street Lighting", "Underground Drainage", "24/7 Security", "Landscaped Entrance"],
    highlights: ["VMRDA Approved", "Budget Friendly", "Clear Title", "Developing Area", "High Appreciation", "Bank Loan Available"],
  },
  {
    id: "northstar-golden-valley",
    title: "NorthStar - Golden Valley",
    location: "Madhurawada",
    city: "Visakhapatnam",
    type: "apartment",
    status: "ongoing",
    price: "₹1.1 Cr onwards",
    priceValue: 11088000,
    area: "1540 - 2240 sq.ft",
    areaValue: 1540,
    bedrooms: 3,
    bathrooms: 3,
    description: "Golden Valley is a premium high-rise apartment project by Northstar Constructions spread across 5.64 acres in Madhurawada. Featuring 2 towers of 24 floors each (Tower A: 10 flats/floor, Tower B: 12 flats/floor) with spacious apartments ranging from 1540 to 2240 sft. The project boasts a massive 33,000 sft clubhouse — one of the largest in the locality — designed for lifestyle, recreation and community activities. Priced at ₹7,200/sft with world-class amenities and superior construction quality.",
    shortDesc: "Premium 24-floor twin towers by Northstar with 33,000 sft clubhouse in Madhurawada.",
    image: "/NORTH.jpg",
    images: ["/NORTH.jpg"],
    amenities: ["Grand Clubhouse (33,000 sft)", "Swimming Pool", "Gymnasium", "Children's Play Area", "Jogging Track", "Landscaped Gardens", "Multipurpose Hall", "24/7 Security", "CCTV Surveillance", "Power Backup"],
    brochureUrl: "/North Star Golden Valley (1).pdf",
    highlights: ["5.64 Acres Township", "24-Floor Twin Towers", "1540-2240 sft Apartments", "₹7,200/sft (Negotiable)", "33,000 sft Clubhouse", "East & West Facing", "Near IT Hubs & Highways", "Bank Loan Available"],
  },
  {
    id: "prasanthi-nilayam",
    title: "Prasanthi Nilayam",
    location: "Anandapuram",
    city: "Visakhapatnam",
    type: "plot",
    status: "completed",
    price: "₹12 Lakhs onwards",
    priceValue: 1200000,
    area: "100 - 200 sq.yds",
    areaValue: 900,
    description: "Peaceful residential plotting project offering tranquil living environment with essential infrastructure and clear documentation.",
    shortDesc: "Peaceful residential plots with tranquil living environment.",
    image: "/PRASANTI.jpg",
    images: ["/PRASANTI.jpg"],
    amenities: ["Gated Community", "Wide Roads", "Underground Drainage", "Street Lighting", "Parks", "24/7 Security"],
    highlights: ["Approved Layout", "Completed Project", "Clear Title", "Peaceful Location", "Affordable", "Ready for Construction"],
  },
  {
    id: "rudra-seniors",
    title: "Rudra Seniors",
    location: "Kommadi",
    city: "Visakhapatnam",
    type: "apartment",
    status: "ongoing",
    price: "₹50 Lakhs onwards",
    priceValue: 5000000,
    area: "990 - 1245 sq.ft",
    areaValue: 990,
    bedrooms: 2,
    bathrooms: 2,
    description: "Rudhra Seniors is a thoughtfully designed high-rise residential project exclusively crafted for senior citizen living, combining comfort, safety, and community-focused lifestyle. Developed with modern architecture, efficient planning, and senior-friendly infrastructure, the project offers 2 BHK apartments in sizes of 990, 1190, 1230 & 1245 sft with spacious layouts, good ventilation and natural light. Features include in-house clinic, pharmacy, grocery store, reading room, multipurpose hall, guest rooms, multiple passenger lifts, wide corridors and a peaceful secure environment.",
    shortDesc: "Premium senior living apartments with in-house healthcare & community facilities in Kommadi.",
    image: "/rudra.jpg",
    images: ["/rudra.jpg"],
    amenities: ["In-house Clinic", "Pharmacy", "Grocery Store", "Reading Room", "Multipurpose Hall", "Guest Rooms", "Multiple Lifts + Service Lift", "Wide Corridors", "Walking Paths", "Community Seating", "Open Sit-out Areas", "24/7 Security", "Administrative Office", "Power Backup"],
    brochureUrl: "/Rudra Senior Floor plans-1(1) (1).pdf",
    highlights: ["Exclusively for Senior Citizens", "2 BHK: 990-1245 sft", "In-house Healthcare & Pharmacy", "Senior-Friendly Design", "Multiple Lifts & Wide Corridors", "Near Schools, Hospitals & Market", "Peaceful Community Living", "Well-Connected Location"],
  },
  {
    id: "siri-nirman-blue-arena",
    title: "SIRI NIRMAN - Blue Arena",
    location: "Kommadi",
    city: "Visakhapatnam",
    type: "apartment",
    status: "ongoing",
    price: "₹45 Lakhs onwards",
    priceValue: 4530500,
    area: "1105 - 1140 sq.ft",
    areaValue: 1105,
    bedrooms: 2,
    bathrooms: 2,
    description: "Blue Arena is a modern 5-floor premium apartment project with 6 spacious flats per floor on a land extent of 1114 sq.yds. Offers East & North facing apartments in 1105 sft and 1140 sft configurations at ₹4,100/sft (negotiable) with amenities charges of ₹3 Lakhs. Features car parking (100 sft), lift facility, CCTV security, walking track, open gym on terrace, open air theatre, and EV charging points. A perfect choice for peaceful family living with spacious, ventilated, modern lifestyle.",
    shortDesc: "Modern 5-floor apartments with terrace gym & open air theatre at ₹4,100/sft.",
    image: "/blue arena.jpg",
    images: ["/blue arena.jpg"],
    amenities: ["Car Parking (100 sft)", "Lift Facility", "Spacious Staircase", "CCTV Security", "Walking Track", "Open Gym @ Terrace", "Open Air Theatre", "EV Charging Points"],
    highlights: ["5 Floors, 6 Flats/Floor", "1105 & 1140 sft", "₹4,100/sft (Negotiable)", "East & North Facing", "Land: 1114 Sq.Yds", "Amenities: ₹3 Lakhs", "EV Charging Points", "Terrace Gym & Theatre"],
    brochureUrl: "/Blue Arena (1) (1).pdf",
  },
  {
    id: "sss-dream-homes",
    title: "SSS Dream Homes",
    location: "Anandapuram",
    city: "Visakhapatnam",
    type: "villa",
    status: "ongoing",
    price: "₹72 Lakhs onwards",
    priceValue: 7200000,
    area: "1600 - 2800 sq.ft",
    areaValue: 1600,
    bedrooms: 3,
    bathrooms: 3,
    description: "Affordable luxury villas designed to fulfill your dream of owning a beautiful independent home with modern amenities.",
    shortDesc: "Affordable luxury villas for your dream independent home.",
    image: "/images/projects/chitra-vilasa-1.jpg",
    images: ["/images/projects/chitra-vilasa-1.jpg"],
    amenities: ["Gated Community", "Clubhouse", "Children's Play Area", "Jogging Track", "24/7 Security", "Power Backup", "Landscaped Gardens", "Community Hall"],
    highlights: ["VMRDA Approved", "Independent Villas", "Vastu Compliant", "Affordable Luxury", "Growing Location", "Home Loan Available"],
    brochureUrl: "/SSS HOMES (1).pdf",
  },
  {
    id: "sss-grand-homes",
    title: "SSS Grand Homes",
    location: "PM Palem",
    city: "Visakhapatnam",
    type: "apartment",
    status: "ongoing",
    price: "₹60 Lakhs onwards",
    priceValue: 6000000,
    area: "1200 sq.ft",
    areaValue: 1200,
    bedrooms: 2,
    bathrooms: 2,
    description: "SSS Grand Homes is located at HPCL Layout, PM Palem offering spacious 1200 sft flats with East & West facing options. Priced at ₹5,000/sft with amenities charges of ₹3 Lakhs. UDS of 36 sq.yds on a land extent of 360 sq.yds. A premium residential project with quality construction, modern amenities, excellent connectivity, and a peaceful family-friendly environment.",
    shortDesc: "Spacious 1200 sft flats at ₹5,000/sft in HPCL Layout, PM Palem.",
    image: "/images/projects/chitra-vilasa-1.jpg",
    images: ["/images/projects/chitra-vilasa-1.jpg"],
    amenities: ["Gated Community", "Quality Construction", "Modern Amenities", "Parking", "24/7 Security", "Power Backup"],
    highlights: ["1200 sft Flats", "₹5,000/sft", "East & West Facing", "UDS: 36 Sq.Yds", "Land Extent: 360 Sq.Yds", "Amenities: ₹3 Lakhs", "HPCL Layout, PM Palem", "Excellent Connectivity"],
    brochureUrl: "/sss 2 (1).pdf",
  },
  {
    id: "sss-sunrise",
    title: "SSS Sunrise",
    location: "Revulapalem",
    city: "Visakhapatnam",
    type: "villa",
    status: "ongoing",
    price: "₹98 Lakhs onwards",
    priceValue: 9805000,
    area: "1850 sq.ft",
    areaValue: 1850,
    bedrooms: 3,
    bathrooms: 3,
    description: "SSS Sunrise is located at Revulapalem (Srinivasa School back side) offering East-facing homes of 1850 sft at ₹5,300/sft. The project comes with a land extend of 275 sq.yds, UDS of 55 sq.yds, and amenities charges of ₹3 Lakhs. Ideal for families seeking spacious, well-connected homes with excellent ventilation and natural light.",
    shortDesc: "East-facing 1850 sft homes at ₹5,300/sft in Revulapalem.",
    image: "/images/projects/chitra-vilasa-1.jpg",
    images: ["/images/projects/chitra-vilasa-1.jpg"],
    amenities: ["Gated Community", "Wide Roads", "Parks", "Street Lighting", "Underground Drainage", "24/7 Security"],
    highlights: ["East Facing", "1850 sft", "₹5,300/sft", "UDS: 55 Sq.Yds", "Land Extend: 275 Sq.Yds", "Amenities: ₹3 Lakhs"],
    brochureUrl: "/sss sun rise 2.pdf",
  },
  {
    id: "yaksha-abode",
    title: "Yaksha Abode",
    location: "Gambeeram",
    city: "Visakhapatnam",
    type: "apartment",
    status: "ongoing",
    price: "₹40 Lakhs onwards",
    priceValue: 4000000,
    area: "1000 - 1400 sq.ft",
    areaValue: 1000,
    bedrooms: 2,
    bathrooms: 2,
    description: "Yaksha Abode is a premium 2-acre gated community in Gambeeram with 5 floors and 29 flats per floor. Offers 2 BHK (1000, 1020, 1030, 1050, 1150 sft) and 3 BHK (1400 sft) apartments at ₹4,000/sft with amenities charges of ₹4 Lakhs. Features swimming pool, clubhouse, gymnasium, mini theatre, children's play area, indoor games, ample car parking, lift facility, 24/7 water supply, power backup, CCTV surveillance, and round-the-clock security. Located in a rapidly developing residential locality with excellent connectivity to Madhurawada, IT Hub and major areas.",
    shortDesc: "Premium 2-acre gated community with 5 floors, 29 flats/floor at ₹4,000/sft in Gambeeram.",
    image: "/yaksha abode.jpg",
    images: ["/yaksha abode.jpg"],
    amenities: ["Swimming Pool", "Club House", "Gymnasium", "Mini Theatre", "Children's Play Area", "Indoor Games & Sports", "Ample Car Parking", "Lift Facility", "24/7 Water Supply", "Power Backup", "CCTV Surveillance", "24/7 Security"],
    highlights: ["2 Acres Gated Community", "5 Floors, 29 Flats/Floor", "2 & 3 BHK (1000-1400 sft)", "₹4,000/sft", "Amenities: ₹4 Lakhs", "Swimming Pool & Mini Theatre", "Near IT Hub & Madhurawada", "Rapidly Developing Locality"],
  },
  {
    id: "yaksha-pride",
    title: "Yaksha Pride",
    location: "Anandapuram",
    city: "Visakhapatnam",
    type: "villa",
    status: "ongoing",
    price: "₹1.2 Cr onwards",
    priceValue: 12000000,
    area: "2867 - 3302 sq.ft",
    areaValue: 2867,
    bedrooms: 4,
    bathrooms: 4,
    description: "Yaksha Pride is a premium gated community of 41 exclusive Triplex Villas spread across 2 acres in Anandapuram, attached to National Highway 16. Built by Abhilasha Constructions, the project offers East & West facing villas in sizes ranging from 2867 sft to 3302 sft on plots of 154-177 sq.yds. Features a banquet hall, guest rooms, swimming pool, gymnasium, indoor games, mini basketball court, and pickleball court. Designed for luxury, privacy and modern family living with direct NH-16 access.",
    shortDesc: "41 exclusive triplex villas on NH-16 with premium amenities in Anandapuram.",
    image: "/images/projects/chitra-vilasa-1.jpg",
    images: ["/images/projects/chitra-vilasa-1.jpg"],
    amenities: ["Banquet Hall", "Guest Rooms", "Gymnasium", "Indoor Games Room", "Swimming Pool", "Mini Basketball Court", "Pickleball Court", "Reception & Lounge", "Gated Community", "24/7 Security"],
    brochureUrl: "/YAKSHA PRIDE BROCHURE WEB (1).pdf",
    highlights: ["41 Exclusive Triplex Villas", "2 Acres Gated Community", "2867-3302 sft Villas", "Attached to NH-16", "East & West Facing", "By Abhilasha Constructions", "Swimming Pool & Sports", "High Growth Corridor"],
  },
];

export function getPropertyById(id: string): Property | undefined {
  return properties.find((p) => p.id === id);
}

export function filterProperties(filters: {
  type?: string;
  status?: string;
  minPrice?: number;
  maxPrice?: number;
  location?: string;
  search?: string;
}): Property[] {
  return properties.filter((p) => {
    if (filters.type && filters.type !== "all" && p.type !== filters.type) return false;
    if (filters.status && filters.status !== "all" && p.status !== filters.status) return false;
    if (filters.minPrice && p.priceValue < filters.minPrice) return false;
    if (filters.maxPrice && p.priceValue > filters.maxPrice) return false;
    if (filters.location && filters.location !== "all" && p.location !== filters.location) return false;
    if (filters.search) {
      const q = filters.search.toLowerCase();
      return (
        p.title.toLowerCase().includes(q) ||
        p.location.toLowerCase().includes(q) ||
        p.type.toLowerCase().includes(q)
      );
    }
    return true;
  });
}
